name: test-application
on: push
jobs:
  build-test-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: action/checkout@v4
      - name: Install
        run: make setup
      - name: Test
        run: make test
      - name: Check
        run: make lint
