name: test-application
on: push
jobs:
  build-test-application:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '26.x'
          cache: 'npm'
      - name: Install
        run: make setup
      - name: Test
        run: make test
      - name: Check
        run: make lint
